module CrystGLFW
  module Event
    # A WindowKeyEvent is generated by the `Window#on_key` callback and contains a `Key` along with
    # an interface to determine what action occurred with the key.
    struct WindowKey < Any
      include Modifiers

      getter window : Window
      getter key    : Key
      getter action : Action

      # :nodoc:
      def initialize(window : Window, key : Key, action : Action, modifiers : Int32)
        @window = window
        @key    = key
        @action = action
        set_modifiers modifiers
      end

    end
  end
end
